apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
data:
  Strict-Transport-Security: "max-age=63072000"
  Referrer-Policy: "same-origin"
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "DENY"
  X-XSS-Protection: "1; mode=block"
