apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemmy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemmy-ui
  template:
    metadata:
      labels:
        app: lemmy-ui
    spec:
      containers:
        - name: lemmy-ui
          image: dessalines/lemmy-ui:0.19.5
          ports:
            - containerPort: 1234
              name: http
          env:
            - name: LEMMY_UI_LEMMY_INTERNAL_HOST
              value: "lemmy:8536"
            - name: LEMMY_UI_LEMMY_EXTERNAL_HOST
              value: "lemmy.schlunker.com:443"
            - name: LEMMY_HTTPS
              value: "true"
            - name: RUST_LOG
              value: "debug"

---

apiVersion: v1
kind: Service
metadata:
  name: lemmy-ui
spec:
  selector:
    app: lemmy-ui
  ports:
    - port: 1234
      name: http
      targetPort: http
