apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:heschlie/gitops.git
    path: homelab/apps
    targetRevision: main
    kustomize:
