apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.5.1
    path: homelab/k8s/kube-prometheus
    helm:
      releaseName: kube-prometheus
      values: |
        namespaceOverride: monitoring
        
        grafana:
          replicas: 1
          podAnnotations:
            match-regex.version-checker.io/grafana: '(\d+)\.(\d+)\.(\d+)'
          defaultDashboardsTimezone: US/Pacific
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.k8s
          persistence:
            enabled: true
            storageClassName: rook-ceph-block
            accessModes:
              - ReadWriteOnce
            size: 20Gi
            finalizers:
              - kubernetes.io/pvc-protection
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            scrapeConfigSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: rook-ceph-block
                  resources:
                    requests:
                      storage: 40Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.k8s
        cleanPrometheusOperatorObjectNames: true
        prometheus-node-exporter:
          prometheus:
            monitor:
              attachMetadata:
                node: true
              relabelings:
                - action: replace
                  sourceLabels:
                    - __meta_kubernetes_node_name
                  targetLabel: instance