grafana:
  defaultDashboardsTimezone: US/Pacific
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.k8s
  persistence:
    enabled: true
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.k8s
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 40Gi
cleanPrometheusOperatorObjectNames: true