apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

images:
  - name: registry.k8s.io/external-dns/external-dns
    newName: heschlie/external-dns
    newTag: v0.15.1-278-g27c24c0b

resources:
  - namespace.yaml
  - external-dns.yaml