apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

images:
  - name: registry.k8s.io/external-dns/external-dns
    newName: tjouve/external-dns
    newTag: 6a4d8474

resources:
  - namespace.yaml
  - external-dns.yaml