apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.16.7
    helm:
      releaseName: cilium
      valuesObject:
        upgradeCompatibility: "1.15"
        cluster:                                                                                                                                                   
          name: kubernetes
        operator:
          replicas: 1
        routingMode: tunnel
        tunnelProtocol: vxlan
        cni:
          exclusive: false
