apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/heschlie/gitops
    path: homelab/k8s/ingress-nginx
    targetRevision: main
    kustomize: