apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant-forward
  namespace: argocd
spec:
  destination:
    namespace: homeassistant
    name: in-cluster
  project: default
  source:
    repoURL: git@github.com:heschlie/gitops.git
    path: homelab/k8s/home-assistant-forward
    targetRevision: main