apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    name: istio
  project: default
  source:
    repoURL: git@github.com:heschlie/gitops.git
    path: homelab/k8s/istio
    targetRevision: main
