apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-forward
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    name: in-cluster
  project: default
  source:
    repoURL: git@github.com:heschlie/gitops.git
    path: homelab/k8s/jellyfin-forward
    targetRevision: main