apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lemmy-database
  namespace: argocd
spec:
  destination:
    namespace: lemmy
    name: in-cluster
  project: default
  source:
    repoURL: git@github.com:heschlie/gitops.git
    path: homelab/k8s/lemmy-database
    targetRevision: main