apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-app
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    repoURL: git@github.com:heschlie/gitops.git
    path: homelab/k8s/kube-prometheus
    targetRevision: main
