apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: version-checker
spec:
  selector:
    matchLabels:
      app: version-checker
  endpoints:
    - port: web
      path: /metrics
