apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr

images:
  - name: lscr.io/linuxserver/sabnzbd
    newTag: 5.0.4-ls258
  - name: lscr.io/linuxserver/sonarr
    newTag: 4.0.17.2952-ls313
  - name: lscr.io/linuxserver/radarr
    newTag: 6.2.1.10461-ls305
  - name: lscr.io/linuxserver/bazarr
    newTag: v1.5.6-ls350
  - name: lscr.io/linuxserver/lidarr
    newTag: 3.1.0.4875-ls30
  - name: lscr.io/linuxserver/jackett
    newTag: v0.24.2045-ls428
  - name: lscr.io/linuxserver/prowlarr
    newTag: 2.4.0.5397-ls149
  - name: haugene/transmission-openvpn
    newTag: 5.4.1
  - name: golift/notifiarr
    newTag: 0.9.5
  - name: lscr.io/linuxserver/lazylibrarian
    newTag: d58c5eab-ls299
  - name: ghcr.io/cleanuparr/cleanuparr
    newTag: 2.9.13

resources:
  - namespace.yaml
  - gateway.yaml
  - sabnzbd.yaml
  - transmission.yaml
  - jackett.yaml
  - notifiarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - anime.yaml
  - bazarr.yaml
  - bazarr-anime.yaml
  - lidarr.yaml
  - prowlarr.yaml
  - lazylibrarian.yaml
  - cleanuparr.yaml

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1whitelist-source-range"
        value: "192.168.0.0/16"