kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  enable-real-ip: "true"
  forwarded-for-header: proxy_protocol
  allow-snippet-annotations: "true"
