apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/cloud/deploy.yaml
  - service-metrics.yaml
  - service-monitor.yaml

patches:
  - path: service-lb-patch.yaml
  - path: target-control-node.yaml
  - path: configmap-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
    path: deploymentPatch.yaml