apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.17.1
spec:
  loadBalancerClass: kube-vip.io/kube-vip-class
  externalTrafficPolicy: Local
