apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-1
        value: --kubelet-insecure-tls
    target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
